apiVersion: v1
kind: Pod
metadata:
  name: restart-nerver
spec:
  containers:
    - name: alpine-container
      image: alpine
      command: ["sleep","1d"]
  restartPolicy:  Never
---
apiVersion: v1
kind: Pod
metadata:
  name: nop
spec:
  containers:
    - name: alpine-container
      image: alpine
      command: ["sleep","1d"]