apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: nginx-rs
spec:
  minReadySeconds: 5
  replicas: 4
  selector:
    matchLabels:
      app: nginx
      ver: "1.23"
  template:
    metadata:
      name: nginx-pod
      labels:
        app: nginx
        ver: "1.23"
    spec:
      containers:
        - name: nginx-container
          image: nginx
          ports:
            - containerPort: 80
              protocol: TCP
