apiVersion: apps/v1
kind: DaemonSet
metadata: 
  name: test
spec:
  minReadySeconds: 5
  selector:
    matchLabels:
      app: "nginx"
      ver: "1.23"
  template:
    metadata:
      name: test daemon
      labels:
        app: "nginx"
        ver: "1.23"
    spec:
      containers:
        - name: nginx-container
          image: nginx
          command:
            - sleep
            - 1d