---
apiVersion: v1
kind: Pod
metadata:
  name: activity3
spec:
  containers:
    - name: alpine test
      image: alpine
      command:
        - sleep
      args:
        - 1d
  restartPolicy: Never      
---
apiVersion: v1
kind: Pod
metadata:
  name: activity2
spec:
  containers:
    - name: alpine test
      image: alpine
      command:
        - sleep
      args:
        - 1d
  restartPolicy: OnFailure
  ---
  apiVersion: v1
kind: Pod
metadata:
  name: activity1
spec:
  containers:
    - name: alpine test
      image: alpine
      command:
        - sleep
      args:
        - 1d
  
