apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: rs
  labels:
    app: jenkins
spec:
  minReadySeconds: 3
  replicas: 6
  selector:
    matchLabels:
      app: jenkins
      ver: "1.1"
  template:
    metadata:
      name: jenkins
      labels:
        app: jenkins
        ver: "1.1"
    spec:
      initContainers: 
        - name: alpine
          image: alpine
          command: ["ping","-c","google.com"]
      restartPolicy: Never
      containers:
        - name: jenkins
          image: jenkins/jenkins
          ports:
            - containerPort: 80
              protocol: TCP
  