apiVersion: v1
kind: Pod
metadata:
  name: vol-pod
  labels:
    purpos: "mount"
spec:
  containers:
    - name: mysql
      image: mysql:8-debian
      ports:
        - containerPort: 3306
          protocol: TCP
      env:
        - name: MYSQL_ROOT_PASSWORD
           value: rootroot
        - name: MYSQL_DATABASE
          value: employees
        - name: MYSQL_USER
          value: bhanu
        - name: MYSQL_PASSWORD
          value: bhanu
      volumeMounts:
        - name: mysql
          mountPath: /var/lib/mysql
  volumes: 
    - name: mysql
      emptyDir: